[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"
command = "npm ci --omit=dev"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10